# Generated by Django 4.0.2 on 2022-03-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencias', to='bank.banco')),
            ],
            options={
                'unique_together': {('numero', 'banco')},
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='bank.agencia')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='bank.titular')),
            ],
            options={
                'unique_together': {('numero', 'agencia_id')},
            },
        ),
    ]
